name: Release
on:
  push:
    branches:
      - main
      - beta
      - abstract
jobs:
  release:
    name: Release
    environment:
      name: production
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          ref: abstract
          submodules: "true"
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: Clean install
        run: |
          rm -rf node_modules
          rm -rf .yarn/cache
          rm -rf .yarn/install-state.gz

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build SDK's
        run: yarn g:build

      - name: Create NPM RC
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          echo "workspace=false" >> .npmrc
          echo "workspaces=false" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Release Needed SDK's
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn g:release -- --debug --force
