name: Release

on:
  push:
    branches:
      - main
      - beta
      - abstract

jobs:
  release:
    name: Release
    environment:
      name: production
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          ref: abstract
          submodules: "true"
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 20

      - name: Install dependencies
        run: yarn --immutable --no-workspaces

      - name: Build SDK's
        run: yarn g:build

      - name: Release Needed SDK's
        env:
          NPM_CONFIG_USERCONFIG: /dev/null
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn g:release -- --debug --force
