name: Release
on:
  push:
    branches:
      - main
      - beta
      - abstract
jobs:
  release:
    name: Release
    environment:
      name: production
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          ref: abstract
          submodules: "true"
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 20

      - name: Clean install
        run: |
          rm -rf node_modules
          rm -rf .yarn/cache
          rm -rf .yarn/install-state.gz

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build SDK's
        run: yarn g:build

      - name: Release Needed SDK's
        env:
          NPM_CONFIG_USERCONFIG: /dev/null
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          # Add these environment variables to handle workspace issues
          NPM_CONFIG_WORKSPACE: "false"
          NPM_CONFIG_WORKSPACES: "false"
        run: |
          # Disable workspaces for npm commands
          npm config set workspaces false
          npm config set workspace false
          # Run the release command with no-workspaces flag
          yarn g:release -- --debug --force --no-workspaces
